apiVersion: v1
kind: Namespace
metadata:
  name: ai-search-engine
  labels:
    name: ai-search-engine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-search-config
  namespace: ai-search-engine
data:
  MONGODB_URI: "mongodb://mongodb:27017/search_engine"
  REDIS_URL: "redis://redis:6379/0"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  CACHE_TTL: "3600"
  FLASK_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-search-secrets
  namespace: ai-search-engine
type: Opaque
data:
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmU=  # base64 encoded
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: ai-search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-search-secrets
              key: MONGO_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "search_engine"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ai-search-engine
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: ai-search-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

